name: Release

on:
  release:
    types: [created]

jobs:
  ghcr:
    name: Publish to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: true
          target: php-fpm
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/stackmasters/php-sample:fpm-${{ github.event.release.name }}
            ghcr.io/stackmasters/php-sample:fpm-latest
      - uses: docker/build-push-action@v5
        with:
          push: true
          target: nginx
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/stackmasters/php-sample:nginx-${{ github.event.release.name }}
            ghcr.io/stackmasters/php-sample:nginx-latest
